# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(blank=True, verbose_name='référence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('picture', models.TextField(verbose_name='Image')),
            ],
            options={
                'verbose_name': 'disque',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'artiste',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Demande effectuée le')),
                ('contacted', models.BooleanField(default=False, verbose_name='Demande traitée')),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Album')),
            ],
            options={
                'verbose_name': 'réservation',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='e-mail')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'prospect',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Contact'),
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='disks', to='store.Artist'),
        ),
    ]
