# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170728_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.TextField(verbose_name='Image'),
        ),
    ]
