# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField()),
                ('created_at', models.DateTimeField(verbose_name='Date de création')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(verbose_name='Demande effectuée le')),
                ('contacted', models.BooleanField(default=False)),
                ('disk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manager.Disk')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='disk',
            name='artists',
            field=models.ManyToManyField(to='manager.Artist'),
        ),
    ]
